environment:
  matrix:
  - nodejs_version: "12"
install:
  - npm install
test_script:
  - node --version
  - npm --version
  - npm run test
build: off
before_test:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
  - createdb testdb
services:
  - postgresql101
